
USE db_escuela;

CREATE TABLE ubigeo (
  ID_DEP varchar(2) NOT NULL,
  ID_PRO varchar(2) NOT NULL,
  ID_DIS varchar(2) NOT NULL,
  NOMBRE_DEP varchar(200) DEFAULT NULL,
  NOMBRE_PRO varchar(200) DEFAULT NULL,
  NOMBRE_DIS varchar(200) DEFAULT NULL,
  PRIMARY KEY (ID_DEP,ID_PRO,ID_DIS)
);


CREATE TABLE escuela_conduccion (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUC VARCHAR(11) NOT NULL UNIQUE,
    NOMBRE VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(255),
    ESTADO VARCHAR(50),
    TELEFONO VARCHAR(15),
    CORREO VARCHAR(100),

    ID_DEP VARCHAR(2),
    ID_PRO VARCHAR(2),
    ID_DIS VARCHAR(2),
    
    ACTIVO TINYINT DEFAULT 1,

    CONSTRAINT fk_ubigeo FOREIGN KEY (ID_DEP, ID_PRO, ID_DIS) REFERENCES ubigeo(ID_DEP, ID_PRO, ID_DIS)
);


DELIMITER $$ 

CREATE PROCEDURE sp_insert_escuela(
    IN P_RUC VARCHAR(11),
    IN P_NOMBRE VARCHAR(150),
    IN P_DIRECCION VARCHAR(255),
    IN P_ESTADO VARCHAR(50),
    IN P_TELEFONO VARCHAR(15),
    IN P_CORREO VARCHAR(100),
    IN P_ID_DEP VARCHAR(2),
    IN P_ID_PRO VARCHAR(2),
    IN P_ID_DIS VARCHAR(2),
    OUT P_ID_GENERADO INT
)
BEGIN
    INSERT INTO escuela_conduccion 
        (RUC, NOMBRE, DIRECCION, ESTADO, TELEFONO, CORREO, 
         ID_DEP, ID_PRO, ID_DIS, ACTIVO)
    VALUES 
        (P_RUC, P_NOMBRE, P_DIRECCION, P_ESTADO, P_TELEFONO, P_CORREO, 
         P_ID_DEP, P_ID_PRO, P_ID_DIS, 1);

    SET P_ID_GENERADO = LAST_INSERT_ID();
END$$

DELIMITER ;


DELIMITER $$
CREATE PROCEDURE sp_listar_escuelas(
    IN P_ID_DEP VARCHAR(2),
    IN P_ID_PRO VARCHAR(2),
    IN P_ID_DIS VARCHAR(2),
    IN P_RUC VARCHAR(11)
)
BEGIN
    SELECT 
        ID, RUC, NOMBRE, DIRECCION, ESTADO, TELEFONO, CORREO, 
        ID_DEP, ID_PRO, ID_DIS, ACTIVO
    FROM escuela_conduccion
    WHERE ACTIVO = 1
      AND (P_ID_DEP IS NULL OR ID_DEP = P_ID_DEP)
      AND (P_ID_PRO IS NULL OR ID_PRO = P_ID_PRO)
      AND (P_ID_DIS IS NULL OR ID_DIS = P_ID_DIS)
      AND (P_RUC IS NULL OR RUC = P_RUC);
END$$
DELIMITER ;


DELIMITER $$

CREATE PROCEDURE sp_buscar_escuela(IN P_ID INT)
BEGIN
    SELECT 
      ID, RUC, NOMBRE, DIRECCION, ESTADO, TELEFONO, CORREO, 
		ID_DEP, ID_PRO, ID_DIS, ACTIVO
    FROM escuela_conduccion
    WHERE ID = P_ID
      and ACTIVO = 1;
END$$

DELIMITER ;


DELIMITER $$

CREATE PROCEDURE sp_update_escuela(
    IN P_ID INT,
    IN P_RUC VARCHAR(11),
    IN P_NOMBRE VARCHAR(150),
    IN P_DIRECCION VARCHAR(255),
    IN P_ESTADO VARCHAR(50),
    IN P_TELEFONO VARCHAR(15),
    IN P_CORREO VARCHAR(100),
    IN P_ID_DEP VARCHAR(2),
    IN P_ID_PRO VARCHAR(2),
    IN P_ID_DIS VARCHAR(2)
)
BEGIN
    UPDATE escuela_conduccion
    SET 
        RUC = P_RUC,
        NOMBRE = P_NOMBRE,
        DIRECCION = P_DIRECCION,
        ESTADO = P_ESTADO,
        TELEFONO = P_TELEFONO,
        CORREO = P_CORREO,
        ID_DEP = P_ID_DEP,
        ID_PRO = P_ID_PRO,
        ID_DIS = P_ID_DIS
    WHERE ID = P_ID;
END$$

DELIMITER ;

DELIMITER $$

CREATE PROCEDURE sp_delete_escuela(
    IN P_ID INT
)
BEGIN
    UPDATE escuela_conduccion
    SET ACTIVO = 0
    WHERE ID = P_ID;
END$$

DELIMITER ;